# Generated by Django 2.0 on 2019-04-29 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('summery', models.TextField()),
                ('content', models.TextField()),
                ('start', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('end', models.DateField()),
                ('map', models.CharField(max_length=300)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='festival/thumbnail')),
                ('file', models.FileField(upload_to='')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_phone', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('supervision', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('confirm', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=150)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Festival')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='festival',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Region'),
        ),
        migrations.AddField(
            model_name='festival',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='festival.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Festival'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'festival')},
        ),
    ]
