# Generated by Django 2.0 on 2019-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='main_image',
            field=models.ImageField(default='', upload_to='', verbose_name='festival/Region/main_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='', verbose_name='festival/Region/thumbnail'),
            preserve_default=False,
        ),
    ]
